### ISSUE TITLE
GPU support

### ISSUE THREAD

**Issue by harindercnvrg** [Vishnunkumar/craft_hw_ocr#1]
Hello, 

The code
`
from craft_hw_ocr import OCR
ocr = OCR.load_models()

def do_ocr(inp):
  img, results = OCR.detection(inp, ocr[2])
  bboxes, text = OCR.recoginition(img, results, ocr[0], ocr[1])
  return OCR.visualize(img, results), text
`
is very slow. Is there a way we can use GPU for detection and recognition models to speed up the inference?

**Comment by Vishnunkumar** [comment]
Hi,

I will be working on the same in the near future and will add capabilities to make use of GPU if available.

**Comment by harindercnvrg** [comment]
Hello, can you give me a brief overview of what changes I would need to make to support gpu inference?

**Comment by Vishnunkumar** [comment]
Hi, 

Please use the following snippet to use CUDA, also ensure cuda is installed properly in your machine to make use of GPU

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
